version: '3.8'

services:
    postgres:
        image: postgres:15-alpine
        container_name: product-db
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: productdb
        ports:
            - "543:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - flip-amol-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin -d productdb"]
            interval: 10s
            timeout: 5s
            retries: 5

    product-service:
        build: ./product-service
        container_name: product-service
        ports:
            - "8080:8080"
        environment:
            DATABASE_URL: postgres://admin:password@postgres:5432/productdb
            depends_on:
            postgres:
            condition: service_healthy
        networks:
            - flip-amol-network
        depends_on:
            - postgres

networks:
    flip-amol-network:
        driver: bridge

volumes:
    postgres_data:


